### ISSUE TITLE
Getting issues while running on Windows 10

### ISSUE THREAD

**Issue by hhashmi** [tomyitav/apollo-typed-lambda#172]
I cloned and tried to run this code 

"npm run build"

and getting following error. Same time it works fine on Mac and Ubuntu

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'build' ]
2 info using npm@6.9.0
3 info using node@v10.16.3
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle @tomyitav/apollo-typed-lambda@1.0.0~prebuild: @tomyitav/apollo-typed-lambda@1.0.0
6 verbose lifecycle @tomyitav/apollo-typed-lambda@1.0.0~prebuild: unsafe-perm in lifecycle true
7 verbose lifecycle @tomyitav/apollo-typed-lambda@1.0.0~prebuild: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;F:\zzz\apollo-typed-lambda\node_modules\.bin;C:\ProgramData\DockerDesktop\version-bin;C:\Program Files\Docker\Docker\Resources\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\nodejs\;C:\Program Files (x86)\Bitvise SSH Client;C:\Program Files\Git\cmd;C:\Users\Huang-PC\AppData\Local\Microsoft\WindowsApps;C:\Users\Huang-PC\AppData\Roaming\npm;C:\Users\Huang-PC\AppData\Local\Programs\Microsoft VS Code\bin
8 verbose lifecycle @tomyitav/apollo-typed-lambda@1.0.0~prebuild: CWD: F:\zzz\apollo-typed-lambda
9 silly lifecycle @tomyitav/apollo-typed-lambda@1.0.0~prebuild: Args: [ '/d /s /c', 'npm run clean && npm run generate' ]
10 silly lifecycle @tomyitav/apollo-typed-lambda@1.0.0~prebuild: Returned: code: 1  signal: null
11 info lifecycle @tomyitav/apollo-typed-lambda@1.0.0~prebuild: Failed to exec prebuild script
12 verbose stack Error: @tomyitav/apollo-typed-lambda@1.0.0 prebuild: `npm run clean && npm run generate`
12 verbose stack Exit status 1
12 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:301:16)
12 verbose stack     at EventEmitter.emit (events.js:198:13)
12 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
12 verbose stack     at ChildProcess.emit (events.js:198:13)
12 verbose stack     at maybeClose (internal/child_process.js:982:16)
12 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
13 verbose pkgid @tomyitav/apollo-typed-lambda@1.0.0
14 verbose cwd F:\zzz\apollo-typed-lambda
15 verbose Windows_NT 10.0.14393
16 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
17 verbose node v10.16.3
18 verbose npm  v6.9.0
19 error code ELIFECYCLE
20 error errno 1
21 error @tomyitav/apollo-typed-lambda@1.0.0 prebuild: `npm run clean && npm run generate`
21 error Exit status 1
22 error Failed at the @tomyitav/apollo-typed-lambda@1.0.0 prebuild script.
22 error This is probably not a problem with npm. There is likely additional logging output above.
23 verbose exit [ 1, true ]

```

**Comment by tomyitav** [comment]
Hi @hhashmi, thanks for reaching out!
Please run the command ```npm run build:win```
It will execute matching commands to run on a windows machine.
I hope it helps!
